Parse the ELF file locally and push to API
kernelci/kernelci-build pull request #14
Opened 2017-03-08 10:45 UTC by mattface

Ripped the elf.py out from the backend, to use it on the builder to extract the extra data bits from vmlinux.

2017-03-08 11:35 UTC, mattface commented
Don't merge this until we are sure python-pyelftools is installed on all the builders

2017-03-08 11:36 UTC, MiloCasagrande commented
Thanks Matt! Looks good!
Before merging this though I also need to update the backend so we have the support there as well.

2017-03-08 14:50 UTC, mattface commented
This is ready to be merged, but I'd like to wait on Kevin as it's mostly his build script

2017-03-08 14:50 UTC, MiloCasagrande commented
@khilman when you are online, can you take a look if everything is fine and merge?

2017-03-08 15:57 UTC, khilman commented
First observation, ansible need an update for the builders to have the python elftools 👍 

```
[...]
found vmlinux, parsing sizes
Traceback (most recent call last):
  File "/home/khilman/bin/build.py", line 416, in <module>
    import elf
  File "/work/kernel/ci/kernelci-build/elf.py", line 16, in <module>
    import elftools.elf.constants as elfconst
ImportError: No module named elftools.elf.constants
```

2017-03-08 16:11 UTC, MiloCasagrande commented
@khilman where did you run that script?
We already updated all the builders to install pyelf...

2017-03-08 16:15 UTC, khilman commented
@MiloCasagrande I ran it locally (and also didn't notice that the ansible requirement was already mentioned in the logs, sorry for the noise.

2017-03-08 16:17 UTC, MiloCasagrande commented
No worries, I though we missed to update one builder.

2017-03-08 16:55 UTC, khilman requested changes

2017-03-08 16:55 UTC, khilman commented on build.py
> +        os.remove(vmlinux_file)
Why remove the vmlinux file locally.  

This will cause make to rebuild on subsequent rebuilds, even if source hasn't changed.

2017-03-08 16:55 UTC, khilman commented on build.py
> +        os.remove(vmlinux_file)
Maybe better is to just remove the shutil.copy() command a bit later that copies vmlinux to the install dir.

2017-03-09 12:59 UTC, mattface commented
Updated. No longer delete the vmlinux, just dont copy it into the install_dir, and a quick cleanup of the http post requests because I found unhandled errors which would result in the build failing.

2017-03-09 17:25 UTC, khilman commented
@mattface can you separate out the ELF stuff from the http post stuff into separate commits?

2017-03-09 17:40 UTC, mattface commented
If I do it won't be until middle of next week, as I've had enough of kernelci for now :) Not your fault ;)

2017-03-09 18:01 UTC, khilman requested changes

2017-03-09 18:01 UTC, khilman commented on build.py
>          bmeta["vmlinux_file"] = "vmlinux"
Shouldn't we also remove the vmlinux_file from the build.json since it's no longer uploaded?

2017-03-09 18:05 UTC, khilman commented
OK, I've cherry-picked this patch and modified it slightly, dropping the post/retry stuff as well as removing the print message and the vmlinux_file field from the build.json.

I've applied it to the master branch, so will close this pull request.  Please submit a follow-up patch for the post/retry stuff.

2017-03-09 18:05 UTC, closed without merging