add kselftest-enabled kernel build (v2)
kernelci/kernelci-build pull request #28
Opened 2017-07-07 22:02 UTC by khilman

There is not static kconfig fragment for kselftests. Rather, each individual kselftest comes with a config fragment for the kernel features it needs.

In order to enable a kselftest-enabled kernel build we need to

1. Dynamically create a combined kconfig fragment (patch #1)
2. Enable it as one of the defconfigs built by downstream jobs (patch #2)

Merging this pull request will enable one additional kernel build (base_defconfig + kselftest fragment) for each architecture.

2017-07-07 22:03 UTC, khilman commented
Changes since v1:
- the kernel/configs/kselftest.config fragment file now will have comments which show the filenames of the original fragments that get combined together.  This makes the fragment more human-readable, and also easier to diagnose/debug potential problems later.

2017-07-08 06:33 UTC, mattface requested changes

2017-07-08 06:33 UTC, mattface commented on jenkins/kernel-trigger-tarball.sh
> +KSELFTEST_FRAG=kernel/configs/kselftest.config
You need to do all this above the "cd ${WORKSPACE}" line, as you're no longer inside the kernel tree at this point. I made that change on kernelci-build-staging

https://github.com/kernelci/kernelci-build-staging/commit/e95f96442fe16fdaaf98535aae6f6d8fcfe546b1

In fact can you remake this pull request on kernelci-build-staging

2017-07-10 19:41 UTC, khilman commented
Reworked and submitted against staging.

2017-07-10 19:41 UTC, closed without merging